require 'fileutils'

namespace :signature do

  _ROOT_DIR = File.expand_path("../../", __FILE__)
  _TARGET_DIR    = File.join(_ROOT_DIR, %w( lib whois record ))
  _SOURCE_DIR    = File.join(_ROOT_DIR, %w( spec signatures responses ))
  _SOURCE_PARTS  = _SOURCE_DIR.split("/")

  task :generate => :generate_signatures

  task :generate_signatures do
    target_path = File.join(_TARGET_DIR, "signature.rb")


    signatures_by_parser = ""
    parsers_by_signature = ""
    signatures = {}
    
    # Loop through the txt files
    Dir.glob("#{_SOURCE_DIR}/**/*.txt").each do |source_path|
      
      parts = (source_path.split("/") - _SOURCE_PARTS)
      khost = parts.shift
      kfile = parts.join("_")
      txt_path = source_path.gsub(".expected", ".txt")
      lines = File.open(source_path, "r:UTF-8")
      puts "Reading... " + source_path

      keywords = Set.new()
      lines.each do |line|
        line = line.strip()

        # I'm using Aho Corasick to perform multi-pattern search
        # within a whois data. The lines below replace the character 
        # '^' with '\n' to indicate that we want the keyword to be
        # at the beginning of sentence

        if (line.start_with?("^"))
          line = line.sub("^","\n")
        end

        if !line.empty?
          keywords.add(line)
          signatures[line] = (signatures[line] || Set.new) + ["#{khost}__#{kfile}"]
        end
      end

      if keywords.count > 0
        signatures_by_parser += "            \"#{khost}__#{kfile}\" => #{keywords.to_a.sort().to_s},\n"
      end
    end

    signatures.each { |k,v| 
      parsers_by_signature += "            #{k.inspect} => #{v.to_a.sort().to_s},\n"
    }

    signature = <<-RUBY
# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want regenerate the content of this file, please
# update the txt files under 
#
#  /spec/signature/responses
# 
# then run following rake task
#
#   $ rake signature:generate
#

require 'aho_corasick'

module Whois
  class Record
    class Signature
      @@signatures_by_parser = {
#{signatures_by_parser} 
      }

      @@parsers_by_signature = {
#{parsers_by_signature} 
      }

      @@matcher = AhoCorasick.new(*@@parsers_by_signature.keys)

      def self.signatures_by_parser
        @@signatures_by_parser
      end

      def self.parsers_by_signature
        @@parsers_by_signature
      end  

      def self.matcher
        @@matcher
      end

    end
  end
end
    RUBY

    File.write(target_path, signature)
  end
end